# Generated by Django 4.0.2 on 2022-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dgb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentrochoi', models.CharField(max_length=500)),
                ('theloai', models.CharField(max_length=400)),
                ('cachchoi', models.CharField(max_length=300)),
            ],
        ),
    ]
